name: scan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload to code artifact
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: *
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }} # or ${{ secrets.github_pat_name }} if you're using a PAT
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with: 
          name: dependency-results.sbom.json
          path:  dependency-results.sbom.json
